name: Populate README

on:
  push:
    paths:
      - '.project'
      - 'README.md'
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout without persisting the GITHUB_TOKEN
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # IMPORTANT: prevents the GITHUB_TOKEN from being stored in Git's credential helper
          persist-credentials: false
          fetch-depth: 1

      # 2) Now that the default remote isn't using GITHUB_TOKEN, reset 'origin' to use your PAT
      - name: Configure origin to use PAT
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}

      # 3) Set up Python to run our README-populating script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-dotenv

      - name: Replace placeholders in README
        run: python .github/scripts/populate_readme.py

      # 4) Finally, commit & push using your PAT-backed remote
      - name: Commit and push updated README
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config --global user.name "readme-bot"
          git config --global user.email "actions@github.com"
          
          git add README.md
          git commit -m "Auto-populated README from .project" || echo "No changes to commit"
          git push origin HEAD

